"""In-tree PEP 517 backend: stage the distribution payload into the package.

The lifecycle installer copies real files — skills, `tools/ai_docs`, `AGENTS.md`
— into a user's project. Those files live once in this repository, which is the
right place for them: duplicating them under `ainative/` would give the stack two
copies of its own method to keep in sync.

But a user who runs `pip install` on a machine with no checkout has only the
wheel. So the payload is *materialised at build time* instead of being tracked
twice: this backend copies the authoritative files into `ainative/_payload/`
just before setuptools builds, and `ainative/lifecycle/source.py` reads them
from there when no checkout is present.

`ainative/_payload/` is generated and git-ignored. Editing it has no effect —
edit the source of truth at the repository root.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from setuptools import build_meta as _setuptools

ROOT = Path(__file__).resolve().parent
PAYLOAD = ROOT / "ainative" / "_payload"

# What a project install needs, and nothing more. The wheel does not carry the
# test suite, the docs archive or the anti-debt agent.
PAYLOAD_TREES = ("skills", "tools/ai_docs", "templates")
PAYLOAD_FILES = ("AGENTS.md", "VERSION", "conventions.json",
                 "docs/VERIFIED-WORK-PLANE.md")
EXCLUDED = {"__pycache__", ".pytest_cache", "tests"}


def _copy_tree(relative: str) -> None:
    source = ROOT / relative
    if not source.is_dir():
        return
    target = PAYLOAD / relative
    shutil.copytree(
        source, target, dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(*EXCLUDED, "*.pyc", "config.sh"))


def stage_payload() -> Path:
    """Refresh `ainative/_payload/` from the authoritative sources."""

    if PAYLOAD.exists():
        shutil.rmtree(PAYLOAD)
    PAYLOAD.mkdir(parents=True)
    for relative in PAYLOAD_TREES:
        _copy_tree(relative)
    for relative in PAYLOAD_FILES:
        source = ROOT / relative
        if not source.is_file():
            continue
        destination = PAYLOAD / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    (PAYLOAD / "PAYLOAD.md").write_text(
        "Generated by _build_backend.py at build time. Do not edit: the sources "
        "of truth are at the repository root.\n", encoding="utf-8")
    return PAYLOAD


# --- PEP 517 hooks: stage, then delegate ---------------------------------


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    stage_payload()
    return _setuptools.build_wheel(wheel_directory, config_settings, metadata_directory)


def build_sdist(sdist_directory, config_settings=None):
    stage_payload()
    return _setuptools.build_sdist(sdist_directory, config_settings)


def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
    # An editable install runs from the checkout, which `source.py` prefers
    # anyway; staging keeps the two paths identical rather than only one tested.
    stage_payload()
    return _setuptools.build_editable(wheel_directory, config_settings, metadata_directory)


get_requires_for_build_wheel = _setuptools.get_requires_for_build_wheel
get_requires_for_build_sdist = _setuptools.get_requires_for_build_sdist
get_requires_for_build_editable = _setuptools.get_requires_for_build_editable
prepare_metadata_for_build_wheel = _setuptools.prepare_metadata_for_build_wheel
prepare_metadata_for_build_editable = _setuptools.prepare_metadata_for_build_editable
