"""Install the stack into user-level agent directories, recording ownership.

Two frontends share this module and nothing else: `scripts/install_agents.py`
(checkout-only, adds vault-protocol validation) and `ainative machine init`
(the installed CLI). The ownership rules, the managed blocks and the manifest
write live here once.

A machine install is reversible by construction: every link, block and
rendered file is recorded in `~/.ai-native/machine.json` (machine.save) with
the proof needed to remove it later — see `machine.py`. On Windows, directory
links fall back to junctions when symlink creation is denied.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import re
from pathlib import Path

from . import machine
from .machine import METHOD_BEGIN, METHOD_END, VAULT_BEGIN, VAULT_END

GENERATED = "Generated by ainative machine"

# Slug grammar mirrored from vault_protocol.SLUG_RE so a bad slug is
# rejected at the CLI without round-tripping through the vault.
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


@dataclasses.dataclass
class InstallReport:
    changes: int
    errors: int
    assets: int
    dry_run: bool
    check: bool
    manifest: Path | None
    stack_root: str


class Installer:
    def __init__(self, stack: Path, home: Path, dry_run: bool, check: bool,
                 vault: Path | None, slug: str | None, printer=print) -> None:
        self.stack = Path(stack).resolve()
        self.home = Path(home).resolve()
        self.dry_run = dry_run
        self.check = check
        self.errors = 0
        self.changes = 0
        self.vault = vault
        self.slug = slug
        self.printer = printer
        # What this run established ownership of, for ~/.ai-native/machine.json.
        self.assets: list[dict] = []

    def _record(self, kind: str, target: Path, **fields: object) -> None:
        """One machine-owned asset. Recorded on OK as well as on write: a
        re-run must not drop the record of something it still owns."""

        try:
            relative = target.resolve().relative_to(self.home).as_posix()
        except (OSError, ValueError):
            relative = target.as_posix()
        record = {"kind": kind, "path": relative, **fields}
        if record not in self.assets:
            self.assets.append(record)

    def report(self, status: str, path: Path, detail: str = "") -> None:
        suffix = f" ({detail})" if detail else ""
        self.printer(f"[{status}] {path}{suffix}")

    def directory(self, path: Path) -> None:
        if path.is_dir():
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", path)
        elif self.dry_run:
            self.report("CREATE", path)
        else:
            path.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _points_at(target: Path, source: Path) -> bool:
        """True when `target` is a link this stack owns, pointing at `source`.

        `is_symlink()` returns False for a Windows directory junction, so a
        junction we created ourselves used to be reported as an unmanaged
        path — making `--check` fail on every Windows install we had done.
        Comparing resolved paths covers symlinks and junctions alike.
        """
        if not target.exists() and not target.is_symlink():
            return False
        try:
            return target.resolve() == source
        except OSError:
            return False

    def link(self, source: Path, target: Path) -> None:
        source = source.resolve()
        if not source.exists() and not source.is_symlink():
            # A payload install carries fewer assets than a checkout; a source
            # this distribution does not ship is skipped, never turned into a
            # broken link.
            self.report("SKIP", target, f"not in this distribution: {source}")
            return
        if self._points_at(target, source):
            self.report("OK", target)
            self._record("link", target, source=str(source))
            return
        if target.exists() or target.is_symlink():
            self.errors += 1
            self.report("KEEP", target, "existing path is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("LINK", target, str(source))
            return
        ok, why = machine._create_link(source, target)
        if ok:
            self.report("LINKED", target, str(source))
            self._record("link", target, source=str(source))
        else:
            self.errors += 1
            self.report("FAILED", target, why)

    def _relative(self, target: Path) -> str:
        try:
            return target.resolve().relative_to(self.home).as_posix()
        except (OSError, ValueError):
            return target.as_posix()

    # --- managed blocks ---------------------------------------------------

    def _block_count(self, text: str, begin: str, end: str) -> int:
        """Count balanced begin/end pairs of one block type."""
        begin_count = text.count(begin)
        end_count = text.count(end)
        return min(begin_count, end_count)

    def _replace_block(self, text: str, begin: str, end: str, new_block: str) -> str:
        """Replace the (first) balanced occurrence of a block, leave the rest.

        The contract is one block per kind. If a user accidentally pasted
        two, we replace the first balanced pair and leave the second
        alone — the caller is then responsible for reporting a duplicate
        via `_block_count`.
        """
        start = text.find(begin)
        if start < 0:
            return text
        finish = text.find(end, start + len(begin))
        if finish < 0:
            return text
        finish += len(end)
        return text[:start] + new_block + text[finish:]

    def _append_block(self, text: str, new_block: str) -> str:
        separator = "\n\n" if text.strip() else ""
        return text.rstrip() + separator + new_block + "\n"

    def managed_method_block(self, path: Path, heading: str,
                             preamble: str = "") -> None:
        block = machine.method_block_text(self.stack, heading)
        self._write_managed_block(
            path, block, METHOD_BEGIN, METHOD_END, "method block",
            preamble=preamble, heading=heading,
        )

    def managed_vault_block(self, path: Path, vault: Path, slug: str) -> None:
        """Install the vault-governance block.

        The block is intentionally minimal: it does not copy the contract.
        It points each harness at the vault's root `AGENTS.md`, which in
        turn delegates to the canonical contract.
        """
        block = machine.vault_block_text(vault, slug)
        self._write_managed_block(path, block, VAULT_BEGIN, VAULT_END,
                                  "vault block", vault=str(Path(vault)),
                                  slug=slug)

    def _write_managed_block(self, path: Path, block: str,
                             begin: str, end: str, label: str,
                             preamble: str = "", **extra: object) -> None:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        begin_count = current.count(begin)
        end_count = current.count(end)
        if begin_count != end_count or begin_count > 1:
            # Refuse malformed and fully duplicated blocks alike. Replacing
            # only one balanced pair would leave contradictory instructions.
            self.errors += 1
            self.report(
                "DUPLICATE", path,
                f"{label}: {begin_count} BEGIN marker(s), {end_count} END marker(s)",
            )
            return

        if not current and preamble:
            current = preamble.rstrip() + "\n"

        wanted = (
            self._replace_block(current, begin, end, block)
            if begin in current
            else self._append_block(current, block)
        )
        if current == wanted:
            self.report("OK", path)
            self._record("block", path, begin=begin, end=end, label=label,
                         preamble=preamble, **extra)
            return
        if self.check:
            self.errors += 1
            self.report("STALE", path)
            return
        self.directory(path.parent)
        self.changes += 1
        if self.dry_run:
            self.report("UPDATE", path, label)
        else:
            path.write_text(wanted, encoding="utf-8")
            self.report("UPDATED", path)
            self._record("block", path, begin=begin, end=end, label=label,
                         preamble=preamble, **extra)

    def remove_managed_block(self, path: Path, begin: str, end: str,
                             label: str) -> None:
        """Remove exactly one managed block while preserving user content."""
        if not path.exists():
            self.report("OK", path, f"{label} absent")
            return
        current = path.read_text(encoding="utf-8")
        begin_count = current.count(begin)
        end_count = current.count(end)
        if begin_count == 0 and end_count == 0:
            self.report("OK", path, f"{label} absent")
            return
        if begin_count != 1 or end_count != 1:
            self.errors += 1
            self.report(
                "DUPLICATE", path,
                f"{label}: {begin_count} BEGIN marker(s), {end_count} END marker(s)",
            )
            return
        wanted = self._replace_block(current, begin, end, "")
        if self.check:
            self.errors += 1
            self.report("STALE", path, f"{label} should be absent")
            return
        self.changes += 1
        if self.dry_run:
            self.report("REMOVE", path, label)
            return
        path.write_text(wanted, encoding="utf-8")
        self.report("UPDATED", path, f"{label} removed")

    def rendered_file(self, template: Path, target: Path) -> None:
        if not template.is_file():
            self.report("SKIP", target, f"not in this distribution: {template}")
            return
        try:
            template_ref = template.resolve().relative_to(self.stack).as_posix()
        except ValueError:
            template_ref = str(template)
        wanted = template.read_text(encoding="utf-8")
        wanted = wanted.replace("{{STACK_ROOT_JSON}}", json.dumps(str(self.stack)))
        wanted = wanted.replace("{{STACK_ROOT}}", str(self.stack))
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == wanted:
            self.report("OK", target)
            self._record("rendered", target, template=template_ref,
                         digest=hashlib.sha256(wanted.encode("utf-8")).hexdigest())
            return
        if target.exists() and GENERATED not in current:
            self.errors += 1
            self.report("KEEP", target, "existing file is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING" if not target.exists() else "STALE", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("RENDER", target, str(template))
        else:
            # Bytes, not text mode: `write_text` translates \n to \r\n on
            # Windows, and the recorded digest is of the rendered text, so the
            # file would never match its own record (the EMP-LC-025 class).
            target.write_bytes(wanted.encode("utf-8"))
            self.report("RENDERED", target)
            self._record("rendered", target, template=template_ref,
                         digest=hashlib.sha256(wanted.encode("utf-8")).hexdigest())

# Shared engineering method targets: every supported harness gets the block.
CURSOR_PREAMBLE = (
    "---\n"
    "description: AI Native Dev Stack and Obsidian vault governance\n"
    "alwaysApply: true\n"
    "---\n"
)


def method_targets(home: Path) -> list[tuple[Path, str]]:
    home = Path(home)
    return [
        (home / ".claude" / "CLAUDE.md", ""),
        (home / ".codex" / "AGENTS.md", ""),
        (home / ".config" / "opencode" / "AGENTS.md", ""),
        (home / ".cursor" / "rules" / "ai-native-dev-stack.mdc", CURSOR_PREAMBLE),
        (home / ".gemini" / "GEMINI.md", ""),
        (home / ".mavis" / "agents" / "mavis" / "agent.md", ""),
    ]


def install(home: Path, stack: Path, *, vault: Path | None = None,
            slug: str | None = None, remove_vault_block: bool = False,
            dry_run: bool = False, check: bool = False,
            printer=print) -> InstallReport:
    """Install (or check) the machine integration for every detected harness.

    The same rules as every other lifecycle operation: nothing user-owned is
    overwritten, everything written is recorded, and the manifest is saved
    only after a run that wrote it and failed nowhere.
    """

    home = Path(home)
    stack = Path(stack)
    installer = Installer(stack, home, dry_run, check, vault, slug,
                          printer=printer)

    generic_skills = sorted((stack / "skills").glob("*/SKILL.md"))
    debt_skills = sorted((stack / "stack/agents/anti-debt/skills").glob("*/SKILL.md"))
    skill_sources = [item.parent for item in generic_skills + debt_skills]
    if not skill_sources:
        printer(f"[SKIP] skills: none found under {stack}")

    # ~/.agents is the common skills location for Codex, OpenCode and recent
    # Cursor. Claude keeps its own directory, so expose the same canonical
    # sources there too.
    for root in (home / ".agents/skills", home / ".claude/skills"):
        for source in skill_sources:
            installer.link(source, root / source.name)

    targets = method_targets(home)
    for path, preamble in targets:
        installer.managed_method_block(path, "Shared engineering method",
                                       preamble=preamble)

    # Vault governance: every supported harness gets a second, separate block.
    if vault is not None and slug is not None:
        for path, _preamble in targets:
            installer.managed_vault_block(path, vault, slug)
    elif remove_vault_block:
        for path, _preamble in targets:
            installer.remove_managed_block(path, VAULT_BEGIN, VAULT_END,
                                           "vault block")

    installer.link(stack / "stack/agents/anti-debt",
                   home / ".mavis/agents/anti-debt")

    adapter = stack / "claude-code" / "anti-debt.md"
    if not adapter.is_file():
        adapter = stack / "adapters" / "claude-code" / "anti-debt.md"
    installer.rendered_file(adapter, home / ".claude/agents/anti-debt.md")
    installer.rendered_file(stack / "adapters/opencode/anti-debt.md",
                            home / ".config/opencode/agents/anti-debt.md")
    installer.rendered_file(stack / "adapters/opencode/ai-native-dev-stack.ts",
                            home / ".config/opencode/plugins/ai-native-dev-stack.ts")

    manifest = None
    if not check and not dry_run and not installer.errors:
        # The machine ownership record: written only after the run that made
        # those files ours, and only when nothing failed.
        version_file = stack / "VERSION"
        version = version_file.read_text(encoding="utf-8").strip() if version_file.is_file() else "unknown"
        manifest = machine.save(home, version=version, assets=installer.assets,
                                stack_root=str(stack))
    return InstallReport(changes=installer.changes, errors=installer.errors,
                         assets=len(installer.assets), dry_run=dry_run,
                         check=check, manifest=manifest, stack_root=str(stack))


__all__ = ["GENERATED", "SLUG_RE", "CURSOR_PREAMBLE", "InstallReport",
           "Installer", "install", "method_targets", "METHOD_BEGIN",
           "METHOD_END", "VAULT_BEGIN", "VAULT_END"]
