import type { Plugin } from "@opencode-ai/plugin"
import { readFile } from "node:fs/promises"
import { spawn } from "node:child_process"

// Generated by scripts/install_agents.py; edit this source template, not the installed copy.
const STACK_ROOT = {{STACK_ROOT_JSON}}

// The LOC threshold is read from conventions.json at runtime rather than
// inlined here: hardcoding it made this the fourth copy of the same rule, and
// copies drift. conventions.json is kept aligned with AGENTS.md by CI.
const FALLBACK_BLOCKING_LOC = 1500

interface RunResult {
  code: number | null
  stdout: string
  stderr: string
}

// Runtime-agnostic process runner: the opencode plugin input exposes no
// guaranteed shell, so this plugin must not depend on a Bun-style `$`.
function run(command: string, args: string[], options: { cwd?: string; input?: string } = {}): Promise<RunResult> {
  return new Promise((resolve) => {
    let settled = false
    const done = (result: RunResult) => {
      if (!settled) {
        settled = true
        resolve(result)
      }
    }
    let child
    try {
      child = spawn(command, args, { cwd: options.cwd, stdio: ["pipe", "pipe", "pipe"] })
    } catch {
      done({ code: null, stdout: "", stderr: "spawn failed" })
      return
    }
    let stdout = ""
    let stderr = ""
    child.stdout?.on("data", (chunk) => { stdout += String(chunk) })
    child.stderr?.on("data", (chunk) => { stderr += String(chunk) })
    child.on("error", () => done({ code: null, stdout, stderr: stderr || "spawn error" }))
    child.on("close", (code) => done({ code, stdout, stderr }))
    if (options.input !== undefined) child.stdin?.write(options.input)
    child.stdin?.end()
  })
}

async function blockingLoc(): Promise<number> {
  try {
    const conventions = JSON.parse(await readFile(`${STACK_ROOT}/conventions.json`, "utf8"))
    const value = conventions?.file_size?.blocking
    return typeof value === "number" ? value : FALLBACK_BLOCKING_LOC
  } catch {
    return FALLBACK_BLOCKING_LOC
  }
}

// `python3` does not exist on a default Windows install, where the launcher is
// `python` or `py`. Resolve once, lazily, and cache the answer.
let pythonBin: string | null = null

async function resolvePython(): Promise<string | null> {
  if (pythonBin !== null) return pythonBin || null
  for (const candidate of ["python3", "python", "py"]) {
    const probe = await run(candidate, ["-c", "import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)"])
    if (probe.code === 0) {
      pythonBin = candidate
      return candidate
    }
  }
  pythonBin = ""
  return null
}

export const AiNativeDevStack: Plugin = async ({ directory }) => {
  const workspaceDir = directory || process.cwd()
  const editedFiles = new Map<string, string>()
  const limit = await blockingLoc()

  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "edit" && input.tool !== "write") return

      const filePath = output.args.filePath ?? output.args.file_path
      if (typeof filePath !== "string") return

      let current: string | null = null
      try {
        current = await readFile(filePath, "utf8")
      } catch {
        // Unreadable path (typically a new file): nothing to gate.
      }
      if (current !== null) {
        const lines = current.split("\n").length
        if (lines > limit) {
          throw new Error(
            `LOC gate: ${filePath} has ${lines} lines (blocking limit: ${limit}). ` +
              `Refactor before editing — see AGENTS.md "Code structure".`,
          )
        }
      }
      editedFiles.set(input.callID, filePath)
    },

    "tool.execute.after": async (input) => {
      const filePath = editedFiles.get(input.callID)
      if (!filePath) return
      editedFiles.delete(input.callID)

      const python = await resolvePython()
      if (!python) return // no Python — skip silently rather than break the edit

      const payload = JSON.stringify({
        cwd: workspaceDir,
        tool_name: input.tool,
        tool_input: { file_path: filePath },
      })
      await run(python, [`${STACK_ROOT}/tools/ai_docs/update_on_edit.py`], { cwd: workspaceDir, input: payload })
    },
  }
}