import type { Plugin } from "@opencode-ai/plugin"

// Generated by scripts/install_agents.py; edit this source template, not the installed copy.
const STACK_ROOT = {{STACK_ROOT_JSON}}

// The LOC threshold is read from conventions.json at runtime rather than
// inlined here: hardcoding it made this the fourth copy of the same rule, and
// copies drift. conventions.json is kept aligned with AGENTS.md by CI.
const FALLBACK_BLOCKING_LOC = 1500

async function blockingLoc(): Promise<number> {
  try {
    const conventions = await Bun.file(`${STACK_ROOT}/conventions.json`).json()
    const value = conventions?.file_size?.blocking
    return typeof value === "number" ? value : FALLBACK_BLOCKING_LOC
  } catch {
    return FALLBACK_BLOCKING_LOC
  }
}

// `python3` does not exist on a default Windows install, where the launcher is
// `python` or `py`. Resolve once, lazily, and cache the answer.
let pythonBin: string | null = null

async function resolvePython($: any): Promise<string | null> {
  if (pythonBin !== null) return pythonBin || null
  for (const candidate of ["python3", "python", "py"]) {
    const probe = await $`${candidate} -c "import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)"`
      .quiet()
      .nothrow()
    if (probe.exitCode === 0) {
      pythonBin = candidate
      return candidate
    }
  }
  pythonBin = ""
  return null
}

export const AiNativeDevStack: Plugin = async ({ $, directory }) => {
  const editedFiles = new Map<string, string>()
  const limit = await blockingLoc()

  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "edit" && input.tool !== "write") return

      const filePath = output.args.filePath ?? output.args.file_path
      if (typeof filePath !== "string") return

      const file = Bun.file(filePath)
      if (await file.exists()) {
        const lines = (await file.text()).split("\n").length
        if (lines > limit) {
          throw new Error(
            `LOC gate: ${filePath} has ${lines} lines (blocking limit: ${limit}). ` +
              `Refactor before editing — see AGENTS.md "Code structure".`,
          )
        }
      }
      editedFiles.set(input.callID, filePath)
    },

    "tool.execute.after": async (input) => {
      const filePath = editedFiles.get(input.callID)
      if (!filePath) return
      editedFiles.delete(input.callID)

      const python = await resolvePython($)
      if (!python) return // no Python — skip silently rather than break the edit

      const payload = JSON.stringify({
        cwd: directory,
        tool_name: input.tool,
        tool_input: { file_path: filePath },
      })
      await $`${python} ${STACK_ROOT}/tools/ai_docs/update_on_edit.py`
        .stdin(payload)
        .quiet()
        .nothrow()
    },
  }
}
