#!/usr/bin/env python3
"""
prevent_finding.py — Generate preventive rules from detected findings.

Per ADR-0017 (Layer 3) and V-max design Layer 6 (Prevention Generation).
"""
from __future__ import annotations

import json
import sys
import uuid
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# Rule templates per (category, subcategory, language)
RULE_TEMPLATES = {
    ("code", "complexity", "python"): {
        "tool": "ruff",
        "config_path": "ruff.toml",
        # Valid standalone ruff.toml schema (top-level [lint], not [tool.ruff]).
        "config": """# Generated by anti-debt-agent to prevent re-occurrence
# Source findings: see .debt-scan.json (subcategory=complexity)
[lint]
select = ["C901"]  # mccabe complexity

[lint.mccabe]
max-complexity = 10
""",
    },
    ("code", "complexity", "rust"): {
        "tool": "clippy",
        "config_path": "clippy.toml",
        "config": """# Generated by anti-debt-agent to prevent re-occurrence
# Source findings: see .debt-scan.json (subcategory=complexity)
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 7
""",
    },
    ("security", "secrets_in_code", "any"): {
        "tool": "gitleaks",
        "config_path": ".gitleaks.toml",
        "config": """# Generated by anti-debt-agent to prevent re-occurrence
# Source findings: see .debt-scan.json (subcategory=secrets_in_code)
[extend]
useDefault = true
""",
    },
    ("dependencies", "circular", "python"): {
        "tool": "pydeps",
        "config_path": "pyproject.toml",
        "config": """# Add to pyproject.toml [tool.pydeps] section:
[tool.pydeps]
show_circular = true
""",
    },
    ("dependencies", "circular", "typescript"): {
        "tool": "dependency-cruiser",
        "config_path": ".dependency-cruiser.json",
        "config": """{
  "forbidden": [
    {
      "name": "no-circular",
      "severity": "error"
    }
  ]
}
""",
    },
    ("tests", "coverage_gaps", "python"): {
        "tool": "coverage.py",
        "config_path": ".coveragerc",
        "config": """# Generated by anti-debt-agent
# Source findings: see .debt-scan.json (subcategory=coverage_gaps)
[report]
fail_under = 80
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:"]
""",
    },
}


def generate_rule(
    finding: dict,
    language: str = "python",
    out_dir: Path = Path("."),
) -> Optional[Path]:
    """Generate a preventive rule for a single finding.

    Returns the path of the generated file, or None if no template matches.
    """
    category = finding.get("category")
    subcategory = finding.get("subcategory")
    if not category or not subcategory:
        return None

    template_key = (category, subcategory, language)
    if template_key not in RULE_TEMPLATES:
        # Try "any" language fallback
        template_key = (category, subcategory, "any")
        if template_key not in RULE_TEMPLATES:
            return None

    template = RULE_TEMPLATES[template_key]
    config_path = out_dir / template["config_path"]
    config_path.parent.mkdir(parents=True, exist_ok=True)

    # If file exists, append with separator
    if config_path.exists():
        existing = config_path.read_text(encoding="utf-8")
        if "anti-debt-agent" in existing:
            # Already has our rules, skip
            return None
        new_content = existing + "\n\n" + template["config"]
    else:
        new_content = template["config"]

    config_path.write_text(new_content, encoding="utf-8")
    return config_path


def aggregate_patterns(
    findings: list[dict],
    threshold: int = 3,
) -> dict[tuple[str, str], list[dict]]:
    """Group findings by (category, subcategory) and return only those with >= threshold."""
    grouped: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for f in findings:
        key = (f.get("category", ""), f.get("subcategory", ""))
        grouped[key].append(f)

    # Filter by threshold
    return {k: v for k, v in grouped.items() if len(v) >= threshold}


def generate_regression_test(
    pattern_key: tuple[str, str],
    findings: list[dict],
    out_dir: Path,
) -> Optional[Path]:
    """Generate a real regression test guarding the prevention rule.

    The generated test asserts that the prevention config (created by
    generate_rule) still exists and carries the anti-debt marker — so it FAILS
    if someone deletes or guts the guard, which is exactly the regression we want
    to catch. Returns None for patterns that have no rule template (nothing to
    guard) rather than emitting a tautological pass-always stub.
    """
    category, subcategory = pattern_key
    template = (RULE_TEMPLATES.get((category, subcategory, "python"))
               or RULE_TEMPLATES.get((category, subcategory, "any")))
    if template is None:
        return None
    config_path = template["config_path"]

    test_name = f"test_no_{category}_{subcategory}_regression"
    test_path = out_dir / "tests" / f"{test_name}.py"
    test_path.parent.mkdir(parents=True, exist_ok=True)
    description = findings[0].get("description", "") if findings else ""

    test_content = f'''"""
Auto-generated regression guard for pattern: {category}/{subcategory}

Source findings: {len(findings)} occurrence(s)
Example: {description[:200]}

Fails if the prevention rule ({config_path}) is removed or no longer carries
the anti-debt marker — i.e. if the guard against this pattern is dismantled.
"""
import unittest
from pathlib import Path

CONFIG = Path(__file__).resolve().parent.parent / "{config_path}"


class {test_name.title().replace("_", "")}(unittest.TestCase):
    def test_prevention_rule_present(self):
        self.assertTrue(
            CONFIG.exists(),
            f"prevention rule missing: {{CONFIG}} (pattern {category}/{subcategory})",
        )
        self.assertIn(
            "anti-debt-agent", CONFIG.read_text(encoding="utf-8"),
            "prevention rule no longer carries the anti-debt marker",
        )


if __name__ == "__main__":
    unittest.main()
'''
    test_path.write_text(test_content, encoding="utf-8")
    return test_path


def main() -> int:
    if len(sys.argv) < 2:
        print(json.dumps({"error": "usage: prevent_finding.py <path-to-.debt-scan.json> [out-dir]"}))
        return 1

    scan_path = Path(sys.argv[1])
    out_dir = Path(sys.argv[2] if len(sys.argv) > 2 else ".")
    out_dir.mkdir(parents=True, exist_ok=True)

    if not scan_path.exists():
        print(json.dumps({"error": f"scan not found: {scan_path}"}))
        return 1

    try:
        scan = json.loads(scan_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"invalid JSON: {e}"}))
        return 1

    findings = scan.get("findings", [])
    patterns = aggregate_patterns(findings, threshold=3)

    report = {
        "patterns_detected": len(patterns),
        "rules_generated": [],
        "tests_generated": [],
    }

    for pattern_key, pattern_findings in patterns.items():
        category, subcategory = pattern_key
        # Generate rule
        rule_path = generate_rule(
            pattern_findings[0],
            language="python",  # TODO: detect from project
            out_dir=out_dir,
        )
        if rule_path:
            report["rules_generated"].append({
                "pattern": f"{category}/{subcategory}",
                "tool": RULE_TEMPLATES.get((category, subcategory, "python"), {}).get("tool")
                or RULE_TEMPLATES.get((category, subcategory, "any"), {}).get("tool"),
                "path": str(rule_path),
            })

        # Generate test
        test_path = generate_regression_test(pattern_key, pattern_findings, out_dir)
        if test_path:
            report["tests_generated"].append({
                "pattern": f"{category}/{subcategory}",
                "path": str(test_path),
            })

    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
