#!/usr/bin/env python3
"""Install the shared AI-native stack into user-level agent directories.

Cross-platform: Linux, macOS and Windows. On Windows, directory links fall
back to junctions when symlink creation is denied (junctions need neither
admin rights nor Developer Mode, and Path.resolve() follows them).

Two distinct, separately-managed blocks are written into each supported
agent's instruction file:

  * "Shared engineering method" — the canonical rules from
    `<STACK>/AGENTS.md`, written to be the same on every machine.
  * "Vault governance" — a thin pointer to the project's v4 Obsidian
    vault (when configured), so every harness sees the same authority
    for project status, board, and contracts. The block contains NO
    contract text: it only references the vault and tells the agent
    where to find the contract. This keeps the contract in one place
    (the vault) and prevents a stack release from silently drifting
    away from what the vault actually says.

The two blocks live inside their own BEGIN/END markers so a user-edited
block stays untouched and either block can be removed independently.
`--check` reports the block state for every harness (OK / MISSING /
STALE / DUPLICATE) without writing anything, and `--dry-run` reports
the same actions without committing them.

Usage:
    python3 scripts/install_agents.py [--dry-run] [--check] [--home PATH]
                                      [--vault PATH] [--project-slug SLUG]
                                      [--no-vault-block]
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys

# Shared engineering method — installed unconditionally when a harness
# directory is targeted. The block carries the canonical rules, not a
# pointer; tools without an @file directive depend on it being inline.
METHOD_BEGIN = "<!-- BEGIN AI-NATIVE-DEV-STACK -->"
METHOD_END = "<!-- END AI-NATIVE-DEV-STACK -->"

# Vault governance — installed only when --vault + --project-slug both
# resolve. The block is a pointer, not a copy: every harness is told
# to read the same vault files, and the v4 contract stays single-sourced.
VAULT_BEGIN = "<!-- BEGIN AI-NATIVE-DEV-STACK VAULT -->"
VAULT_END = "<!-- END AI-NATIVE-DEV-STACK VAULT -->"

GENERATED = "Generated by scripts/install_agents.py"

# Slug grammar mirrored from vault_protocol.SLUG_RE so a bad slug is
# rejected at the CLI without round-tripping through the vault. The
# vault's own validator still re-checks; this is a fast, helpful fail.
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def _import_protocol():
    """Lazy import: keep the module usable when the user only wants
    the original "method-only" behaviour and the new files are absent
    from a partial checkout.
    """
    try:
        import vault_protocol  # type: ignore
    except ImportError:
        return None
    return vault_protocol


class Installer:
    def __init__(self, stack: Path, home: Path, dry_run: bool, check: bool,
                 vault: Path | None, slug: str | None) -> None:
        self.stack = stack.resolve()
        self.home = home.resolve()
        self.dry_run = dry_run
        self.check = check
        self.errors = 0
        self.changes = 0
        self.vault = vault
        self.slug = slug

    def report(self, status: str, path: Path, detail: str = "") -> None:
        suffix = f" ({detail})" if detail else ""
        print(f"[{status}] {path}{suffix}")

    def directory(self, path: Path) -> None:
        if path.is_dir():
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", path)
        elif self.dry_run:
            self.report("CREATE", path)
        else:
            path.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _points_at(target: Path, source: Path) -> bool:
        """True when `target` is a link this stack owns, pointing at `source`.

        `is_symlink()` returns False for a Windows directory junction, so a
        junction we created ourselves used to be reported as an unmanaged
        path — making `--check` fail on every Windows install we had done.
        Comparing resolved paths covers symlinks and junctions alike.
        """
        if not target.exists() and not target.is_symlink():
            return False
        try:
            return target.resolve() == source
        except OSError:
            return False

    def link(self, source: Path, target: Path) -> None:
        source = source.resolve()
        if self._points_at(target, source):
            self.report("OK", target)
            return
        if target.exists() or target.is_symlink():
            self.errors += 1
            self.report("KEEP", target, "existing path is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("LINK", target, str(source))
        else:
            self._create_link(source, target)

    def _create_link(self, source: Path, target: Path) -> None:
        """Symlink, falling back to a Windows junction when symlinks are denied.

        Creating a symlink on Windows needs admin rights or Developer Mode.
        A directory junction needs neither and resolves identically for our
        purposes, so it is the pragmatic fallback rather than a hard failure.
        """
        try:
            target.symlink_to(source, target_is_directory=source.is_dir())
            self.report("LINKED", target, str(source))
            return
        except OSError as err:
            if os.name != "nt" or not source.is_dir():
                self.errors += 1
                self.report("FAILED", target, f"{type(err).__name__}: {err}")
                return

        completed = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(target), str(source)],
            capture_output=True, text=True,
        )
        if completed.returncode == 0:
            self.report("JUNCTION", target, str(source))
        else:
            self.errors += 1
            self.report("FAILED", target, (completed.stderr or completed.stdout).strip())

    # --- managed blocks ---------------------------------------------------

    def _block_count(self, text: str, begin: str, end: str) -> int:
        """Count balanced begin/end pairs of one block type."""
        begin_count = text.count(begin)
        end_count = text.count(end)
        return min(begin_count, end_count)

    def _replace_block(self, text: str, begin: str, end: str, new_block: str) -> str:
        """Replace the (first) balanced occurrence of a block, leave the rest.

        The contract is one block per kind. If a user accidentally pasted
        two, we replace the first balanced pair and leave the second
        alone — the caller is then responsible for reporting a duplicate
        via `_block_count`.
        """
        start = text.find(begin)
        if start < 0:
            return text
        finish = text.find(end, start + len(begin))
        if finish < 0:
            return text
        finish += len(end)
        return text[:start] + new_block + text[finish:]

    def _append_block(self, text: str, new_block: str) -> str:
        separator = "\n\n" if text.strip() else ""
        return text.rstrip() + separator + new_block + "\n"

    def managed_method_block(self, path: Path, heading: str) -> None:
        block = (
            f"{METHOD_BEGIN}\n"
            f"## {heading}\n\n"
            f"Read `{self.stack / 'AGENTS.md'}` immediately at session start and treat it "
            "as mandatory shared engineering instructions.\n"
            f"{METHOD_END}"
        )
        self._write_managed_block(path, block, METHOD_BEGIN, METHOD_END, "method block")

    def managed_vault_block(self, path: Path, vault: Path, slug: str) -> None:
        """Install the vault-governance block.

        The block is intentionally minimal: it does not copy the contract.
        It points each harness at the vault's root `AGENTS.md`, which in
        turn delegates to the canonical contract. Anything the agent needs
        to know about the project (board, sessions, rules) is reachable
        through the same single path.
        """
        rel_root = (vault / "AGENTS.md").as_posix()
        rel_project = f"projects/{slug}/AGENTS.md"
        rel_board = f"projects/{slug}/BOARD.md"
        block = (
            f"{VAULT_BEGIN}\n"
            "## Vault governance (v4)\n\n"
            f"This session is bound to the v4 vault at `{vault}`.\n\n"
            f"- Read `{rel_root}` and `{rel_project}` first.\n"
            f"- The board (`{rel_board}`) is the authority for project status.\n"
            f"- Never write into `_system/`, never edit `BOARD.md` directly, "
            "and never invent project context: if the entries are missing, "
            "create a `needs-triage` card and stop.\n"
            f"- Vault location, project slug and validator status are "
            "discovered via `$OBSIDIAN_VAULT` and `$OBSIDIAN_PROJECT_SLUG`. "
            "If either is missing, ask the user before proceeding.\n"
            f"{VAULT_END}"
        )
        self._write_managed_block(path, block, VAULT_BEGIN, VAULT_END, "vault block")

    def _write_managed_block(self, path: Path, block: str,
                             begin: str, end: str, label: str) -> None:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        balanced = self._block_count(current, begin, end)
        duplicates = current.count(begin) - balanced

        if duplicates > 0:
            # Two BEGIN markers with only one END: the block is broken.
            # Refuse to write — auto-rewriting a half-formed block is
            # exactly the kind of silent corruption this installer
            # exists to prevent.
            self.errors += 1
            self.report("DUPLICATE", path, f"{label}: {duplicates + 1} BEGIN without END")
            return

        wanted = (
            self._replace_block(current, begin, end, block)
            if begin in current
            else self._append_block(current, block)
        )
        if current == wanted:
            self.report("OK", path)
            return
        if self.check:
            self.errors += 1
            self.report("STALE", path)
            return
        self.directory(path.parent)
        self.changes += 1
        if self.dry_run:
            self.report("UPDATE", path, label)
        else:
            path.write_text(wanted, encoding="utf-8")
            self.report("UPDATED", path)

    def rendered_file(self, template: Path, target: Path) -> None:
        wanted = template.read_text(encoding="utf-8")
        wanted = wanted.replace("{{STACK_ROOT_JSON}}", json.dumps(str(self.stack)))
        wanted = wanted.replace("{{STACK_ROOT}}", str(self.stack))
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == wanted:
            self.report("OK", target)
            return
        if target.exists() and GENERATED not in current:
            self.errors += 1
            self.report("KEEP", target, "existing file is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING" if not target.exists() else "STALE", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("RENDER", target, str(template))
        else:
            target.write_text(wanted, encoding="utf-8")
            self.report("RENDERED", target)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install method, skills, agents, hooks and v4 vault "
                    "governance for every detected AI CLI."
    )
    parser.add_argument("--home", type=Path, default=Path.home(), help="target home directory")
    parser.add_argument("--dry-run", action="store_true", help="show changes without writing")
    parser.add_argument("--check", action="store_true", help="verify an existing installation")
    parser.add_argument("--vault", type=Path, default=None,
                        help="v4 Obsidian vault path (default: $OBSIDIAN_VAULT). "
                             "When given, every supported harness gets a Vault "
                             "governance block that points to the vault.")
    parser.add_argument("--project-slug", type=str, default=None,
                        help="v4 project slug (default: $OBSIDIAN_PROJECT_SLUG). "
                             "Validated against the v4 grammar before any block is written.")
    parser.add_argument("--no-vault-block", action="store_true",
                        help="skip the vault governance block even when --vault is set "
                             "(use for the v4 setup_check matrix in CI).")
    return parser.parse_args()


def resolve_vault_pair(args: argparse.Namespace) -> tuple[Path | None, str | None, str | None]:
    """Return (vault, slug, error) from --vault/--project-slug + env.

    Returning a single error string (instead of raising) keeps the caller
    in charge of how a configuration problem is reported. The string
    describes the smallest fix the user can apply.
    """
    if args.no_vault_block:
        return (None, None, None)
    protocol = _import_protocol()
    if protocol is None:
        # No protocol module — refuse to invent a vault path, even from
        # the environment. A user wanting vault governance must be on a
        # checkout that ships the protocol layer.
        env_vault = os.environ.get("OBSIDIAN_VAULT")
        env_slug = os.environ.get("OBSIDIAN_PROJECT_SLUG")
        if not env_vault and not env_slug:
            return (None, None, None)
        return (None, None, "vault requested but vault_protocol.py is missing from this checkout")

    vault_path = protocol.resolve_vault_path(args.vault)
    if vault_path is None:
        return (None, None, "no vault path from --vault, positional, or OBSIDIAN_VAULT")
    slug = protocol.validate_slug(args.project_slug or protocol.resolve_project_slug(args.project_slug))
    if slug is None:
        return (None, None, f"invalid project slug {args.project_slug!r}")
    return (vault_path, slug, None)


def main() -> int:
    args = parse_args()
    if args.check and args.dry_run:
        print("ERROR: --check and --dry-run are mutually exclusive.", file=sys.stderr)
        return 2
    if args.vault and args.project_slug and not SLUG_RE.match(args.project_slug):
        print(f"ERROR: --project-slug {args.project_slug!r} does not match v4 grammar",
              file=sys.stderr)
        return 2

    stack = Path(__file__).resolve().parent.parent
    installer = Installer(stack, args.home, args.dry_run, args.check,
                          None, None)

    generic_skills = sorted((stack / "skills").glob("*/SKILL.md"))
    debt_skills = sorted((stack / "stack/agents/anti-debt/skills").glob("*/SKILL.md"))
    skill_sources = [item.parent for item in generic_skills + debt_skills]

    # ~/.agents is the common skills location for Codex, OpenCode and recent Cursor.
    # Claude keeps its own directory, so expose the same canonical sources there too.
    for root in (args.home / ".agents/skills", args.home / ".claude/skills"):
        for source in skill_sources:
            installer.link(source, root / source.name)

    # Shared engineering method: every supported harness gets a copy.
    method_targets = [
        args.home / ".claude" / "CLAUDE.md",
        args.home / ".codex" / "AGENTS.md",
        args.home / ".config" / "opencode" / "AGENTS.md",
        args.home / ".mavis" / "agents" / "mavis" / "agent.md",
    ]
    for path in method_targets:
        installer.managed_method_block(path, "Shared engineering method")

    # Vault governance: every supported harness gets a second, separate
    # block. We resolve once and reuse, so a bad --vault surfaces as one
    # error rather than six.
    vault, slug, vault_err = resolve_vault_pair(args)
    if vault_err:
        print(f"ERROR: {vault_err}", file=sys.stderr)
        return 2
    if vault is not None and slug is not None:
        for path in method_targets:
            installer.managed_vault_block(path, vault, slug)

    installer.link(
        stack / "stack/agents/anti-debt", args.home / ".mavis/agents/anti-debt"
    )

    installer.rendered_file(
        stack / "adapters/opencode/anti-debt.md",
        args.home / ".config/opencode/agents/anti-debt.md",
    )
    installer.rendered_file(
        stack / "claude-code" / "anti-debt.md" if (stack / "claude-code" / "anti-debt.md").is_file()
        else stack / "adapters/claude-code/anti-debt.md",
        args.home / ".claude/agents/anti-debt.md",
    )
    installer.rendered_file(
        stack / "adapters/opencode/ai-native-dev-stack.ts",
        args.home / ".config/opencode/plugins/ai-native-dev-stack.ts",
    )

    mode = "check" if args.check else "dry-run" if args.dry_run else "install"
    print(f"\nStack {mode} ({sys.platform}): {installer.changes} change(s), "
          f"{installer.errors} issue(s).")
    if not args.check:
        print("Restart running AI clients so they reload global rules, skills and plugins.")
    return 1 if installer.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
