#!/usr/bin/env python3
"""Install the shared AI-native stack into user-level agent directories.

Cross-platform: Linux, macOS and Windows. On Windows, directory links fall
back to junctions when symlink creation is denied (junctions need neither
admin rights nor Developer Mode, and Path.resolve() follows them).

Usage:
    python3 scripts/install_agents.py [--dry-run] [--check] [--home PATH]
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys


BEGIN = "<!-- BEGIN AI-NATIVE-DEV-STACK -->"
END = "<!-- END AI-NATIVE-DEV-STACK -->"
GENERATED = "Generated by scripts/install_agents.py"


class Installer:
    def __init__(self, stack: Path, home: Path, dry_run: bool, check: bool) -> None:
        self.stack = stack.resolve()
        self.home = home.resolve()
        self.dry_run = dry_run
        self.check = check
        self.errors = 0
        self.changes = 0

    def report(self, status: str, path: Path, detail: str = "") -> None:
        suffix = f" ({detail})" if detail else ""
        print(f"[{status}] {path}{suffix}")

    def directory(self, path: Path) -> None:
        if path.is_dir():
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", path)
        elif self.dry_run:
            self.report("CREATE", path)
        else:
            path.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _points_at(target: Path, source: Path) -> bool:
        """True when `target` is a link this stack owns, pointing at `source`.

        `is_symlink()` returns False for a Windows directory junction, so a
        junction we created ourselves used to be reported as an unmanaged
        path — making `--check` fail on every Windows install we had done.
        Comparing resolved paths covers symlinks and junctions alike.
        """
        if not target.exists() and not target.is_symlink():
            return False
        try:
            return target.resolve() == source
        except OSError:
            return False

    def link(self, source: Path, target: Path) -> None:
        source = source.resolve()
        if self._points_at(target, source):
            self.report("OK", target)
            return
        if target.exists() or target.is_symlink():
            self.errors += 1
            self.report("KEEP", target, "existing path is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("LINK", target, str(source))
        else:
            self._create_link(source, target)

    def _create_link(self, source: Path, target: Path) -> None:
        """Symlink, falling back to a Windows junction when symlinks are denied.

        Creating a symlink on Windows needs admin rights or Developer Mode.
        A directory junction needs neither and resolves identically for our
        purposes, so it is the pragmatic fallback rather than a hard failure.
        """
        try:
            target.symlink_to(source, target_is_directory=source.is_dir())
            self.report("LINKED", target, str(source))
            return
        except OSError as err:
            if os.name != "nt" or not source.is_dir():
                self.errors += 1
                self.report("FAILED", target, f"{type(err).__name__}: {err}")
                return

        completed = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(target), str(source)],
            capture_output=True, text=True,
        )
        if completed.returncode == 0:
            self.report("JUNCTION", target, str(source))
        else:
            self.errors += 1
            self.report("FAILED", target, (completed.stderr or completed.stdout).strip())

    def managed_instructions(self, path: Path, heading: str) -> None:
        block = (
            f"{BEGIN}\n"
            f"## {heading}\n\n"
            f"Read `{self.stack / 'AGENTS.md'}` immediately at session start and treat it "
            "as mandatory shared engineering instructions.\n"
            f"{END}"
        )
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        start = current.find(BEGIN)
        finish = current.find(END)
        if start >= 0 and finish >= start:
            finish += len(END)
            wanted = current[:start] + block + current[finish:]
        else:
            separator = "\n\n" if current.strip() else ""
            wanted = current.rstrip() + separator + block + "\n"
        if current == wanted:
            self.report("OK", path)
            return
        if self.check:
            self.errors += 1
            self.report("STALE", path)
            return
        self.directory(path.parent)
        self.changes += 1
        if self.dry_run:
            self.report("UPDATE", path, "managed instruction block")
        else:
            path.write_text(wanted, encoding="utf-8")
            self.report("UPDATED", path)

    def rendered_file(self, template: Path, target: Path) -> None:
        wanted = template.read_text(encoding="utf-8")
        wanted = wanted.replace("{{STACK_ROOT_JSON}}", json.dumps(str(self.stack)))
        wanted = wanted.replace("{{STACK_ROOT}}", str(self.stack))
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == wanted:
            self.report("OK", target)
            return
        if target.exists() and GENERATED not in current:
            self.errors += 1
            self.report("KEEP", target, "existing file is not managed by this stack")
            return
        if self.check:
            self.errors += 1
            self.report("MISSING" if not target.exists() else "STALE", target)
            return
        self.directory(target.parent)
        self.changes += 1
        if self.dry_run:
            self.report("RENDER", target, str(template))
        else:
            target.write_text(wanted, encoding="utf-8")
            self.report("RENDERED", target)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install method, skills, agents and supported hooks for every detected AI CLI."
    )
    parser.add_argument("--home", type=Path, default=Path.home(), help="target home directory")
    parser.add_argument("--dry-run", action="store_true", help="show changes without writing")
    parser.add_argument("--check", action="store_true", help="verify an existing installation")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check and args.dry_run:
        print("ERROR: --check and --dry-run are mutually exclusive.", file=sys.stderr)
        return 2

    stack = Path(__file__).resolve().parent.parent
    installer = Installer(stack, args.home, args.dry_run, args.check)

    generic_skills = sorted((stack / "skills").glob("*/SKILL.md"))
    debt_skills = sorted((stack / "stack/agents/anti-debt/skills").glob("*/SKILL.md"))
    skill_sources = [item.parent for item in generic_skills + debt_skills]

    # ~/.agents is the common skills location for Codex, OpenCode and recent Cursor.
    # Claude keeps its own directory, so expose the same canonical sources there too.
    for root in (args.home / ".agents/skills", args.home / ".claude/skills"):
        for source in skill_sources:
            installer.link(source, root / source.name)

    installer.managed_instructions(args.home / ".claude/CLAUDE.md", "Shared engineering method")
    installer.managed_instructions(args.home / ".codex/AGENTS.md", "Shared engineering method")
    installer.managed_instructions(
        args.home / ".config/opencode/AGENTS.md", "Shared engineering method"
    )
    installer.managed_instructions(
        args.home / ".mavis/agents/mavis/agent.md", "Shared engineering method"
    )
    installer.link(
        stack / "stack/agents/anti-debt", args.home / ".mavis/agents/anti-debt"
    )

    installer.rendered_file(
        stack / "adapters/opencode/anti-debt.md",
        args.home / ".config/opencode/agents/anti-debt.md",
    )
    installer.rendered_file(
        stack / "adapters/claude-code/anti-debt.md",
        args.home / ".claude/agents/anti-debt.md",
    )
    installer.rendered_file(
        stack / "adapters/opencode/ai-native-dev-stack.ts",
        args.home / ".config/opencode/plugins/ai-native-dev-stack.ts",
    )

    mode = "check" if args.check else "dry-run" if args.dry_run else "install"
    print(f"\nStack {mode} ({sys.platform}): {installer.changes} change(s), "
          f"{installer.errors} issue(s).")
    if not args.check:
        print("Restart running AI clients so they reload global rules, skills and plugins.")
    return 1 if installer.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
