#!/usr/bin/env python3
"""A stranger's Verified first run, through the CLI only.

Nothing here reads the repository, the tests, or this file's imports: it builds
(or is given) a wheel, installs it in a fresh virtual environment, and follows
the commands the README documents. The contract this proves:

    fresh wheel -> fresh git project -> init --profile verified
    -> trust init (scaffold) -> trust bootstrap -> commit
    -> work admit -> work new -> verify -> converge = CONVERGED

and the refusal battery a user hits by mistake: `{}`, a missing file, invalid
JSON, an unsupported schema, a predicate that contradicts the policy - each one
a stable code, exit 2, no traceback.

The scaffolds are generated by the product. If a step needs a file no command
produced, this script must fail: that is the property being tested.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from ainative_workplane.contracts import generate_uid  # noqa: E402

CHECKS: list[str] = []
PLACEHOLDER_DIGEST = "0" * 64


class Failure(RuntimeError):
    """A step that must not fail did."""


def ok(message: str) -> None:
    CHECKS.append(message)
    print(f"[ok] {message}")


def run(argv, *, cwd=None, env=None, expect=0, timeout=1200):
    completed = subprocess.run([str(item) for item in argv], cwd=cwd,
                               env={**os.environ, **(env or {})},
                               capture_output=True, text=True,
                               stdin=subprocess.DEVNULL, timeout=timeout)
    if expect is not None and completed.returncode != expect:
        raise Failure(f"exit {completed.returncode}, expected {expect}: "
                      + " ".join(map(str, argv))
                      + f"\n--- stdout\n{completed.stdout[-2500:]}"
                      + f"\n--- stderr\n{completed.stderr[-2500:]}")
    return completed


def refuse(argv, *, code: str, cwd=None, env=None):
    completed = run(argv, cwd=cwd, env=env, expect=2)
    combined = completed.stdout + completed.stderr
    if "Traceback" in combined:
        raise Failure(f"a traceback reached the user:\n{combined[-1500:]}")
    if code not in combined:
        raise Failure(f"expected {code} in the refusal, got:\n{combined[-1500:]}")
    return completed


def git(repo: Path, *args: str) -> None:
    run(["git", "-C", str(repo), *args])


def build_artifacts(project: Path, policy: dict, root: dict) -> dict:
    """One requirement, one criterion, one task, one verification. Mirrors the
    shapes the Work Plane documents; every uid is generated by the running CLI
    process where one exists (trust init produced root/policy)."""

    requirement = generate_uid("req")
    criterion = generate_uid("ac")
    task = generate_uid("task")
    verification = generate_uid("verify")
    registry_reference = generate_uid("work")
    registry = {
        "schema_name": "command_registry", "schema_version": 1,
        "commands": {"check": {"argv": [sys.executable, "tests/check.py"],
                               "timeout_seconds": 60,
                               "substance": {"type": "unittest",
                                             "minimum_observations": 1}}},
    }
    return {
        "requirements": [{"schema_name": "requirements", "schema_version": 1,
                          "uid": requirement, "statement": "the value stays one",
                          "acceptance_criteria": [{"uid": criterion,
                                                   "digest": PLACEHOLDER_DIGEST}]}],
        "acceptance_criteria": [{"schema_name": "acceptance_criteria",
                                 "schema_version": 1, "uid": criterion,
                                 "requirement": {"uid": requirement,
                                                 "digest": PLACEHOLDER_DIGEST},
                                 "criterion": "the module still exposes VALUE",
                                 "verification_specifications": [
                                     {"uid": verification, "digest": PLACEHOLDER_DIGEST}]}],
        "tasks": [{"schema_name": "tasks", "schema_version": 1, "uid": task,
                   "requirements": [{"uid": requirement, "digest": PLACEHOLDER_DIGEST}],
                   "implementation_paths": ["src/app.py"]}],
        "verification_specifications": [{
            "schema_name": "verification_specification", "schema_version": 1,
            "uid": verification,
            "acceptance_criteria": [{"uid": criterion, "digest": PLACEHOLDER_DIGEST}],
            "command_registry": {"uid": registry_reference,
                                 "digest": PLACEHOLDER_DIGEST},
            "relationship": "black_box", "execution_scope": ["tests/check.py"],
            "covered_implementation_paths": ["src/app.py"], "dependencies": [],
            "substance_requirement": "unittest",
            "required_evidence_provenance": "GIT_RECORDED", "command": "check"}],
        "project_policy": policy,
        "approval_root": root,
        "command_registry": registry,
    }, verification

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--wheel", default=None,
                        help="a prebuilt wheel (default: build one from this tree)")
    parser.add_argument("--keep", action="store_true")
    args = parser.parse_args()

    workspace = Path(tempfile.mkdtemp(prefix="ainative-verified-e2e-"))
    failed = False
    try:
        if args.wheel:
            wheel = Path(args.wheel).resolve()
            if not wheel.is_file():
                raise Failure(f"wheel not found: {wheel}")
        else:
            dist = workspace / "dist"
            run([sys.executable, "-m", "pip", "wheel", "--disable-pip-version-check",
                 "--no-deps", "--wheel-dir", dist, REPO])
            wheels = sorted(dist.glob("*.whl"))
            if len(wheels) != 1:
                raise Failure(f"expected one wheel, found {wheels}")
            wheel = wheels[0]

        venv = workspace / "venv"
        run([sys.executable, "-m", "venv", venv])
        bindir = venv / ("Scripts" if os.name == "nt" else "bin")
        python = bindir / ("python.exe" if os.name == "nt" else "python")
        cli = bindir / ("ainative.exe" if os.name == "nt" else "ainative")
        run([python, "-m", "pip", "install", "--disable-pip-version-check", "-q",
             "--no-deps", wheel])
        ok(f"fresh venv installed the wheel {wheel.name}")

        project = workspace / "project"
        (project / "src").mkdir(parents=True)
        (project / "tests").mkdir()
        (project / "src" / "app.py").write_text("VALUE = 1\n", encoding="utf-8")
        (project / "tests" / "check.py").write_text(
            "print('Ran 1 test in 0.001s')\nprint('OK')\n", encoding="utf-8")
        git(project, "init", "-q")
        git(project, "config", "user.email", "verified-e2e@example.invalid")
        git(project, "config", "user.name", "Verified E2E")
        git(project, "add", "-A")
        git(project, "commit", "-qm", "initial")

        completed = run([cli, "init", "--profile", "verified", "--project", project])
        ok("init --profile verified succeeded in a fresh Git project")

        doctor = run([cli, "doctor", "--json", "--project", project])
        record = json.loads(doctor.stdout)
        hook = next(item for item in record["environment"]
                    if item["name"] == "claude_hook")
        if hook["status"] != "OK":
            raise Failure(f"the hook is not configured after init: {hook}")
        ok("doctor is green and reports the PostToolUse hook configured")

        scaffold = run([cli, "trust", "init", "--repo", project, "--by", "e2e"])
        scaffold_record = json.loads(scaffold.stdout)
        root_path = Path(scaffold_record["approval_root"])
        policy_path = Path(scaffold_record["policy"])
        if not root_path.is_file() or not policy_path.is_file():
            raise Failure("trust init reported files it did not write")
        if scaffold_record["authority"].startswith("none"):
            ok("trust init wrote the scaffold and claims no authority")
        else:
            raise Failure("trust init claimed authority it cannot have")

        run([cli, "trust", "bootstrap", "--repo", project,
             "--approval-root", root_path, "--policy", policy_path,
             "--by", "e2e", "--predicate", "recorded_owner_ack"])
        git(project, "add", "-A")
        git(project, "commit", "-qm", "trust anchor")
        show = run([cli, "trust", "show", "--repo", project])
        show_record = json.loads(show.stdout)
        if not show_record.get("governed"):
            raise Failure(f"the anchor does not govern its own project: {show_record}")
        ok("trust bootstrap + commit: trust show reports governed")

        policy = json.loads(policy_path.read_text(encoding="utf-8"))
        root = json.loads(root_path.read_text(encoding="utf-8"))
        artifacts, verification_uid = build_artifacts(project, policy, root)
        work_dir = project / ".ai-native" / "work" / "w1"
        artifact_args = [item for name, payload in artifacts.items()
                         for item in ("--artifact",
                                      f"{name}={json.dumps(payload)}")]
        run([cli, "work", "admit", work_dir, "--repo", project, "--by", "e2e",
             *artifact_args])
        git(project, "add", "-A")
        git(project, "commit", "-qm", "work creation approval")
        run([cli, "work", "new", work_dir, *artifact_args])
        git(project, "add", "-A")
        git(project, "commit", "-qm", "work contract")
        ok("work admit + work new: the contract is created under the anchor")

        verified = run([cli, "verify", "--work", work_dir, "--repo", project,
                        "--verification", verification_uid])
        run([cli, "converge", "--work", work_dir, "--repo", project])
        git(project, "add", "-A")
        git(project, "commit", "-qm", "verification evidence")
        converge = run([cli, "converge", "--work", work_dir, "--repo", project])
        if '"verdict":"CONVERGED"' not in converge.stdout.replace(" ", ""):
            raise Failure(f"the governed workflow did not converge:\n{converge.stdout[:1500]}")
        ok("verify + converge through the production boundary: CONVERGED")

        # --- the refusal battery a user hits by mistake ---------------------
        empty = workspace / "empty.json"
        empty.write_text("{}", encoding="utf-8")
        broken = workspace / "broken.json"
        broken.write_text("{not json", encoding="utf-8")
        unsupported = workspace / "unsupported.json"
        unsupported.write_text(json.dumps({"schema_name": "approval_root",
                                           "schema_version": 99}), encoding="utf-8")

        fresh = workspace / "fresh"
        (fresh).mkdir()
        git(fresh, "init", "-q")
        git(fresh, "config", "user.email", "e2e@example.invalid")
        git(fresh, "config", "user.name", "E2E")

        base = [cli, "trust", "bootstrap", "--repo", fresh, "--by", "e2e"]
        refuse([*base, "--approval-root", empty, "--policy", empty], code="TRUST_ROOT_INVALID")
        refuse([*base, "--approval-root", workspace / "missing.json", "--policy", empty],
               code="TRUST_ROOT_INVALID")
        refuse([*base, "--approval-root", broken, "--policy", empty],
               code="TRUST_ROOT_INVALID")
        refuse([*base, "--approval-root", unsupported, "--policy", empty],
               code="TRUST_SCHEMA_UNSUPPORTED")
        refuse([*base, "--approval-root", root_path, "--policy", empty],
               code="TRUST_POLICY_INVALID")
        refuse([cli, "trust", "bootstrap", "--repo", fresh,
                "--approval-root", root_path, "--policy", policy_path,
                "--by", "e2e", "--predicate", "signature"],
               code="TRUST_POLICY_INVALID")
        refuse([cli, "trust", "init", "--repo", project, "--by", "e2e"],
               code="TRUST_SCAFFOLD_EXISTS")
        ok("refusals: {} / missing / invalid JSON / bad schema / bad policy / "
           "predicate mismatch / existing scaffold - stable codes, exit 2, no traceback")

        print(f"\nVERIFIED FIRST RUN: PASS ({len(CHECKS)} checks)")
        return 0
    except Failure as error:
        failed = True
        print(f"\nVERIFIED FIRST RUN: FAIL\n{error}", file=sys.stderr)
        return 1
    finally:
        if args.keep or failed:
            print(f"workspace kept for inspection: {workspace}")
        else:
            shutil.rmtree(workspace, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())